### ISSUE TITLE
Panic: index out of range 

### ISSUE THREAD

**Issue by davehayes** [sapcc/ntp_exporter#141]
So ntp_exporter crashed the other day with this log + backtrace:

```
Dec  6 09:36:46 2024 myhost daemon.notice ntp_exporter[53635] 2024/12/06 09:36:46 WARN: clock drift is above 0.01s, taking multiple measurements for 5.00 seconds
Dec  6 09:37:02 2024 myhost daemon.notice ntp_exporter[53635] 2024/12/06 09:37:02 WARN: clock drift is above 0.01s, taking multiple measurements for 5.00 seconds
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] 2024/12/06 09:37:23 WARN: clock drift is above 0.01s, taking multiple measurements for 5.00 seconds
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] panic: runtime error: index out of range [0] with length 0
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635]
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] goroutine 793913611 [running]:
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] main.calculateMedian({0x0?, 0x0, 0xc2c380?})
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] #011/root/ntp_exporter/collector.go:253 +0x99
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] main.Collector.measure({{0x86c27e07b, 0x12}, 0x4, 0x12a05f200, {0x9426a8, 0x86c184200}, 0x86c046048, 0x86c046040, 0x86c046050, 0x86c046058, ...})
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] #011/root/ntp_exporter/collector.go:206 +0x1225
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] main.Collector.Collect({{0x86c27e07b, 0x12}, 0x4, 0x12a05f200, {0x9426a8, 0x86c184200}, 0x86c046048, 0x86c046040, 0x86c046050, 0x86c046058, ...}, ...)
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] #011/root/ntp_exporter/collector.go:145 +0x58
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] #011/root/ntp_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:455 +0x102
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 793913608
Dec  6 09:37:23 2024 myhost daemon.notice ntp_exporter[53635] #011/root/ntp_exporter/vendor/github.com/prometheus/client_golang/prometheus/registry.go:466 +0x568
```

This is on FreeBSD 13.4 with your 2.5.0 version. Is this something I should worry about? I cannot yet upgrade this box to 2.7.1.

**Comment by Nuckal777** [comment]
Indeed the empty slice case isn't properly handled here: https://github.com/sapcc/ntp_exporter/blob/dba42876ef0219fcdc708e95c88dd0d5f6e320a2/collector.go#L262.

**Comment by SuperSandro2000** [comment]
#143

**Comment by SuperSandro2000** [comment]
I've just published the 2.8.0 release which fixes this bug.
